application:
  location: config (GitHub)
  config:
    profile: dev
    description: valor obtenido desde 'fees-dev.yml'

spring:
  data:
    mongodb:
      database: fees
      port: '27017'
      host: mongo_db

logging:
  level:
    root: info
