application:
  location: config (GitHub)
  config:
    profile: prod
    description: valor obtenido desde 'transaction-service-prod.yml'

spring:
  data:
    mongodb:
      database: transactions
      port: '27017'
      host: localhost

logging:
  level:
    root: info
